### Listar solo activos
GET http://localhost:8002/empleados?estado=activo

### Buscar por área
GET http://localhost:8002/empleados?area=Sistemas

### Buscar por documento
GET http://localhost:8002/empleados?documento=123456